### ISSUE TITLE
the bundled example

### ISSUE THREAD

**Issue by droeatumn** [mourisl/T1K#13]
The README says the example can be run via
`./run-t1k -f kiridx/kiridx_rna_seq.fa -1 example/example_1.bam -2 example/example_2.fa -t 8 -o T1K_example`
but I think it should be
`./run-t1k -f kiridx/kiridx_rna_seq.fa -1 example/example_1.fq -2 example/example_2.fq  -t 8 -o T1K_example`

**Comment by mourisl** [comment]
Thank you for noticing these typos! They should be fixed now.
