### ISSUE TITLE
How to output a bam file

### ISSUE THREAD

**Issue by Ritabear** [mourisl/T1K#14]
Hi~
I need to watch the bam file by IGV. Therefore, I hope the t1k can output a bam file.

Thanks a lot for the help!

**Comment by mourisl** [comment]
BAM file is not easy to generate. I think the best way is to filter your reference file, e.g. hla_ref_{dna,rna}.fa using the representative alleles from the t1k_allele.tsv file, and then extract the allele sequences from the reference fasta file, then build a BWA/Bowtie index and run the alignment on the subset of alleles.

**Comment by Ritabear** [comment]
Thank you so much for helping out.
Sorry, English is not my mother tongue. It seems a bit rude to speak like this above. I am deeply sorry, but I don't mean to offend.

**Comment by mourisl** [comment]
Oh, I was not offended at all. It's just that the BAM file is not straightforward to generate, and using BWA/Bowtie is a more straightforward solution.
