### ISSUE TITLE
Can HLA output file directly used in HATK ?

### ISSUE THREAD

**Issue by alicekiki** [mourisl/T1K#17]
Hi! HATK HLA2HPED module has not directly supported T1K,  i would like to know does any other infomation needed to generate the HATK needed input file? or just the output file can be directly used as the input? Thank you.

**Comment by mourisl** [comment]
I don't think T1K's output is directly compatible with HATK's. Could you please give an example of the expected input of HLA2HPED from the NGS-based inference?
