### ISSUE TITLE
Can FPK be converted to FPKM?

### ISSUE THREAD

**Issue by lucy-tian** [mourisl/T1K#18]
Hi,
I noticed in your paper that the abundance column is normalized to Fragments per Kilobase (FPK).
However, for RNA expression quantification comparison between samples, we will need to normalize by reads to get FPKM.
I just wanted to ask if T1K is able to normalize to FPK to FPKM for expression quantification? Thank you!

**Comment by mourisl** [comment]
FPKM depends on the total read count of your data set, and equals FPK/(read_count/10^6), and the read_count is not stored in T1K. We leave the abundance estimate at FPK level so you can plug in the total read count, by summing the primary alignments from BAM file or counting the rows in fastq files. Some other applications may want to calculate the FPKM based with respect to the reads aligned to the KIR/HLA region. Therefore, the FPK value is more flexible.

**Comment by lucy-tian** [comment]
Thank you!!
