### ISSUE TITLE
FASTQ-Extractor step failes

### ISSUE THREAD

**Issue by Akazhiel** [mourisl/T1K#2]
Hello!

I'm trying to run this tool but doesn't matter the data I use, even with the example data, I always run into the same error.

This is the command I used to run it:
```
run-t1k -f /T1K/hlaidx/hlaidx_dna_seq.fa -1 /input/360RIO055_TCL_DNA_1.fastq.gz -2 /input/360RIO055_TCL_DNA_2.fastq.gz --preset hla -t 50 --od 360RIO055_TCL
```

And this is the error that's reported:

```
system /opt/conda/envs/Nanopore_WGS/bin/fastq-extractor -t 50 -f /T1K/hlaidx/hlaidx_dna_seq.fa -o 360RIO055_TCL/T1K_360RIO055_TCL_DNA_1_candidate  -1 /input/360RIO055_TCL_DNA_1.fastq.gz -2 /input/360RIO055_TCL_DNA_2.fastq.gz failed: 139 at /opt/conda/envs/Nanopore_WGS/bin/run-t1k line 58.
```

I tried running both the tool downloaded from github and the one installed via bioconda and both give the same error.

Thanks,

Jonatan

**Comment by mourisl** [comment]
I think there is something wrong with T1K on the higher gcc version. Could you please try to recompile T1K with gcc <= 7.X? I will fix this issue in the meantime.

**Comment by mourisl** [comment]
I think I've fixed this issue. Coudl you please pull the github repo again, recompile it and give it a try? If it works, I will draft a new version. Thank you.

**Comment by Akazhiel** [comment]
Hello,

The issue seems fixed. I re-downloaded the repo and tried to run it again and finished without any errors. Thanks for the quick fix!

Best regards,
Jonatan

**Comment by mourisl** [comment]
Thank you for testing the updated program. I have drafted a new release, and the bioconda version should be auto bumped soon. I'll close this issue for now, and please feel free to reopen it if you find any other issues.
