### ISSUE TITLE
Problems with copynumber analysis

### ISSUE THREAD

**Issue by jshdydh123** [mourisl/T1K#28]
Hi,I wanted to express my appreciation for your incredible tool.

While utilizing the T1K-copynumber function, I encountered an issue. Specifically, when running the command python3 t1k-copynumber.py -g XXX_genotype.tsv --nomissing KIR3DL3,KIR2DL4,KIR3DP1,KIR3DL2, I observed that in the output file generated by copynumber, several framework genes, such as KIR2DL4, have a log-ratio of 0.00, resulting in a copynumber of 0.

However, upon examining the genotype.tsv file for these genes, I noticed that the abundance of KIR2DL4 is relatively high and the quality score is 60. I am curious about how to interpret this situation and whether there is a solution to address it. 
The sample genotype.tsv file and copynumber output file are shown in the figure.

I appreciate your time and assistance in resolving this matter.

huang
![kir_copynumber](https://github.com/mourisl/T1K/assets/132548865/8cd5e91a-032b-4f75-9012-8e5a8f30e0bc)
![kir_gentype tsv](https://github.com/mourisl/T1K/assets/132548865/5fe52cbd-684c-4be0-9956-8f71cfdb8c25)

**Comment by mourisl** [comment]
The script finds there are two copies for 2DL4 "2DL4*005 2 0.00", the number after the allele (abundance in the original genotype.tsv file), is the number of copies. Though based on your screenshot of the abundance, I think the log-likelihood difference with the next likely copy number should be larger, at least shouldn't be 0.00. Could you please paste the genotype.tsv as a text and I will look into this issue. Thank you.

**Comment by jshdydh123** [comment]
Thank you for your reply.
This is the genotype.tsv file mentioned above.
[t1k_kir_genotype_tsv.txt](https://github.com/mourisl/T1K/files/15141102/t1k_kir_genotype_tsv.txt)

**Comment by mourisl** [comment]
Thank you for sharing the file. The "quality_score" column in the copy number output is the difference of the likelihood, and in this case both likelihood are very small, so the difference becomes less than 0.01. I have changed the value to the difference of log-likelihood (which I think I used this value at some point), so the difference is more obvious now.

**Comment by jshdydh123** [comment]
Thank you very much for your assistance. With the adjustments made to the copynumber function, I have successfully resolved the issue mentioned earlier.
