### ISSUE TITLE
output interpretation - secondary alleles

### ISSUE THREAD

**Issue by YuliuG** [mourisl/T1K#29]
Hi, I was using T1K v.1.0.5 for HLA typing. However, from one of the samples (RNA-seq) I got results contains secondary allele. I tried to google it but I still don't quite understand how to interpret it. As I can see, the quality score for secondary allele is also high. Does this mean the patient is expressing more than two alleles? Could it be a sign of potential mutation on HLA alleles? I'd like to hear your thoughts and interpretation on this one. I appreciate it. 

`HLA-A   2       HLA-A*29:02:01  2338.397334     60      HLA-A*11:01:01  1732.617518     60      HLA-A*11:303;457.673183;60
`

**Comment by mourisl** [comment]
These are alleles that pass the abundance threshold but do not optimize the number of overall explained reads. You can disregard these secondary predictions. They are mainly used for debugging and copy number inference.

**Comment by YuliuG** [comment]
Thank you!

**Comment by punching-samuel** [comment]
Why the quality score is 60 (max) ？
Could you explain how you calculate the quality?

Sammi

**Comment by mourisl** [comment]
The quality score is the negative log p-value, where p-value is calculated based on a Poisson distribution with the background noise as the null hypothesis. You can find more details in the manuscript (copy/paste here):

Genotyping quality score
T1K also scores each called allele to represent the confidence. The principle is to conduct the statistical test that compares the computed abundance with the noise abundance. The noise abundance for one allele A of gene Gi is calculated as Σj≠i αAbund(Gj)sim(Gi, Gj) + βAbund(B), where Abund(Gj) is the abundance of gene j, sim(Gi, Gj) is the sequence similarity between genes Gi and Gj, Abund(B) is abundance for the other allele of gene Gi if it is heterozygous, and α, β are user-defined constants to control the magnitude of noise. We model the abundance as a Poisson distribution and compute the P-value by testing the observed abundance under the hypothesis of noise Poisson distribution. The quality score is reported as −log10(P-value). Similar to the MAPQ in read alignment software like BWA-MEM ([Li and Durbin 2009](https://genome.cshlp.org/content/33/6/923.long#ref-22)), we set 60 as the upper limit of the quality score.

So 60 is kind of pvalue=10^-60, which is an extremely small pvalue.
