### ISSUE TITLE
Found 0 read fragments when assigning stage

### ISSUE THREAD

**Issue by punching-samuel** [mourisl/T1K#34]
Hello, I have used T1K to genotype our scRNA bam data with barcode white list. It runs fine before, but now it cannot find fragment when assigning stage, may owes to the format of my new data. The bam data from both times shared the same gtf and index files. But the latter data cannot assign fragments, they are truly from different sequencing platform.

My codes are like,
![截屏2024-07-03 10 12 26](https://github.com/mourisl/T1K/assets/165863420/9e4d3ca8-d42b-4d8e-8545-17ce5a4d4300)
 
The first bam file is like,
<img width="841" alt="截屏2024-06-27 10 50 58" src="https://github.com/mourisl/T1K/assets/165863420/b4f5e2a8-d53c-46ea-9e1e-c50947251c49">

The second bam file without any results after analyzing is like,
<img width="840" alt="截屏2024-06-27 10 51 26" src="https://github.com/mourisl/T1K/assets/165863420/6b6fc2ab-f001-4132-a11d-c2ef54d0ff83">

My errors are like,
[Fri Jun 28 19:24:57 2024] run-t1k begins.
[Fri Jun 28 19:24:57 2024] SYSTEM CALL:../T1K/bam-extractor -b ../BJZY0108L_name_sorted.bam -t 20 -f ..ref_genome/Kiridx_unzip_ver/_rna_coord.fa -o ../NoCB_BJZY0108L_candidate 
[Fri Jun 28 19:24:57 2024] Start to extract candidate reads from bam file.
[Fri Jun 28 19:34:45 2024] Finish extracting reads.
[Fri Jun 28 19:34:45 2024] SYSTEM CALL:../T1K/genotyper  -o ../NoCB_BJZY0108L -t 20 -f ../ref_genome/Kiridx_unzip_ver/_rna_seq.fa -u ../NoCB_BJZY0108L_candidate.fq
[Fri Jun 28 19:34:45 2024] Found 0 read fragments. Start read assignment.
[Fri Jun 28 19:34:45 2024] Finish read end assignments.
[Fri Jun 28 19:34:45 2024] Finish read fragment assignments. 0 read fragments can be assigned (average -nan alleles/read).
[Fri Jun 28 19:34:45 2024] Finish allele quantification in 2 EM iterations.
[Fri Jun 28 19:34:45 2024] Genotyping finishes.
[Fri Jun 28 19:34:45 2024] SYSTEM CALL: ../T1K/analyzer  -o ../NoCB_BJZY0108L -t 20 -f ../ref_genome/Kiridx_unzip_ver/_rna_seq.fa -a../NoCB_BJZY0108L_allele.tsv -u ../NoCB_BJZY0108L_aligned.fa
[Fri Jun 28 19:34:45 2024] Found 0 read fragments. Start read assignment.
[Fri Jun 28 19:34:45 2024] Finish read end assignments.
[Fri Jun 28 19:34:45 2024] Finish read fragment assignments. 0 read fragments can be assigned (average -nan alleles/read).
[Fri Jun 28 19:34:45 2024] Finish allele quantification in 2 EM iterations.
[Fri Jun 28 19:34:45 2024] Post analysis finishes.
[Fri Jun 28 19:34:45 2024] Finish.

**Comment by punching-samuel** [comment]
I can only guess that the difference in the bam files caused the same coord and reference to work, but the former worked, while the latter had no results. I use pysam to analyze and I can't see the difference in the structure of the bam files.

Best wishes,
Samuel.

**Comment by mourisl** [comment]
The second bam file does not seems to be sorted by coordinate. Could you please check it? If it is not sorted, you can use samtools sort first.

**Comment by punching-samuel** [comment]
> The second bam file does not seems to be sorted by coordinate. Could you please check it? If it is not sorted, you can use samtools sort first.

Thank you for your reply. I will try the suggestions now, although I originally thought that the sequencing platform had already sorted the bam when they were provided.

with regards,
Samuel.

**Comment by punching-samuel** [comment]
> The second bam file does not seems to be sorted by coordinate. Could you please check it? If it is not sorted, you can use samtools sort first.

It truly helps,  thank you for your cooperation～
