### ISSUE TITLE
Multiple paired-end fastq files for the same sample

### ISSUE THREAD

**Issue by Bondada20** [mourisl/T1K#35]
Hello, 

Thanks for this amazing tool.

Any recommendation on the best approach to take when one has multiple paired-end fastq files for the same sample? An example is the 1000 genome 30X WGS files (see attached PNG). I want to infer the HLA types on the WGS data from the 1000 genome project.
![Screenshot 2024-07-20 050648](https://github.com/user-attachments/assets/e971792d-511b-4117-84dc-03df07310172)

**Comment by mourisl** [comment]
You can use wildcard in the file name. For example, "-1 ERR*_1.fastq.gz -2 ERR*_2.fastq.gz" here. It might be better to use all the reads from the sample.

**Comment by Bondada20** [comment]
Thanks!

I ran run-t1k on one of the paired files and the inferred hla type and the results were the **same** when compared to the published sanger sequencing results. But as you said, I will use all the reads from the sample. This might be a lot slower compared to using just one pair (the largest in terms of file size).
