### ISSUE TITLE
Problems with HLA-C

### ISSUE THREAD

**Issue by liu930724** [mourisl/T1K#38]
Hi，

Thanks for this amazing tool and it is the fastest and most convenient tools I have ever used for HLA typing.

We enriched the HLA genes of NA12878 by PCR and sequenced them by PE150, when using the T1K and IMGT/HLA 3.55 databases, only a few samples can obtain the correct C*01:02:01; C*07:01:01(green part below), most of the other samples are C*07:02:01 , C*07:512 or C*07 is missing.
![image](https://github.com/user-attachments/assets/da3dc66f-9112-40e0-8e1f-fed79baf9e8f)

The results of other HLA genes are correct.

I give the 5_candidate_1/2.fq obtained from T1K  to HLA-HD and SpecHLA,  both of them can get the correct typing.
![image](https://github.com/user-attachments/assets/43646027-344b-461c-bb91-4ea920219cd6)

Any sort of guidance would be greatly appreciated!

**Comment by mourisl** [comment]
Thank you for the kind words! What was your running command for T1K?

**Comment by liu930724** [comment]
T1K:
```
run-t1k -1 5_1.fq.gz -2 5_2.fq.gz -t 16 --preset hla -f T1K_ref_dna_seq.fa --cov 30 -o 5.t1k/test
```

SpecHLA:
```
bash script/whole/SpecHLA.sh -n NA12878_5 -1 5_1.fq.gz -2 5_2.fq.gz -o test -j 16
```

**Comment by mourisl** [comment]
Can you also share the output of 5.t1k/test_genotype.tsv? In the table, is the number after the allele ID the abundance inferred by T1K?

**Comment by liu930724** [comment]
Yes. The number after the allele ID is the abundance inferred by T1K.  And the abundance of these wrong types seems to be much lower than the abundance of the correct types.

For example, the NA12878_5 sample (2M pairs reads, PE150, found 791719 read fragments after genotyper), it's abundance between the two alleles varies greatly in T1K, but less in HLAHD and SpecHLA.

The same HLA-C primers were used in all samples and the complete gene was amplified. Only the ratio of primers and PCR conditions are different. Theoretically, the abundance of the two HLA-C alleles should be similar.

T1K:
![image](https://github.com/user-attachments/assets/cffd088c-e8b0-467b-9d58-5cff6415ff15)

SpecHLA (candidate.fq obtained from T1K):
Samples of 4 different HLA-C typings, but in SpecHLA they are all C*01:02:01:01, C*07:01:01:01
![image](https://github.com/user-attachments/assets/beeaf2d2-3af7-41b0-b4ee-e437ff90ad6b)
![image](https://github.com/user-attachments/assets/1f5c27c3-e16f-47d9-acb7-b50e9b7cea26)

hlahd (same input as T1K, but subsample to 1M pairs):
```
bash /home/hlahd.1.7.0/bin/hlahd.sh -t {threads} -m 100 -f {params.freq_data} \
{input.trim_r1} {input.trim_r2} {params.HLA_gene} {params.dictionary} \
{wildcards.sample} {log} 1> {output.map_log} 2>&1
```
![image](https://github.com/user-attachments/assets/e0cf0fa8-631e-457f-97db-8c12e23f18ae)

Because the abundance of the two genotypes of DRB1 in many samples was quite different and the results were correct (DRB1\*01:01:01,5635; DRB1\*03:01:01,1836 in NA12878_5), I did not use the '--frac' parameter for filtering.

In addition, both hlahd and specHLA require HLA allele frequency in populations, I am trying to see how this parameter affects the results of these two softwares.

**Comment by mourisl** [comment]
The low abundance may mean T1K is confused about C*07:01:01 and C*07:512. Since the raw data seems small, could you please share the raw reads with me? Thank you.

**Comment by liu930724** [comment]
Thanks for your help.

I prepared the 4 samples in the SpecHLA above. Each of their candidate_fq files is about 100Mb and can get correct results in SpecHLA.

The size of the trimmed_fq file used for T1K input is about 0.5Gb. Do you need this file? If you need it, I will prepare NA12878_5 for you.

How can I give you these data? Is it convenient to provide an email address?

**Comment by mourisl** [comment]
Yes, one sample's read file is good. My email is Li.Song@dartmouth.edu .

**Comment by mourisl** [comment]
Hi @liu930724 , thank you for sharing the files! I think I've fixed the bug based on sample 5's data. Could you please clone the github repo, recompile T1K and give it a try?

**Comment by liu930724** [comment]
It works! All samples are typed correctly now. Thank you for your help. Cheers~

![image](https://github.com/user-attachments/assets/3edd46ea-7e5e-41f4-940d-b63d6b6c174b)
