### ISSUE TITLE
Providing candidate fq files as input 

### ISSUE THREAD

**Issue by moutsian** [mourisl/T1K#4]
Hi,

When starting genotyping from stage 1 or stage2, the program is looking for the candidate fq files by trying to infer the name from the output directory and prefix. It would be useful to be able to specify where these candidate fq files are as an input argument instead, so that the outputs could be saved in different directories (e.g. for when testing different cov/frac options).

I think there is currently no such input option? Apologies if I've missed it.

Cheers,
Loukas

**Comment by mourisl** [comment]
Could you please try the "--noExtraction" option? Then it should directly use the candidate fq files in other directories.

**Comment by moutsian** [comment]
Thank you very much for the rapid response! 
I used the --noExtraction option and specified candidate reads fq files with -1 and -2 and it works fine indeed.

Cheers,
Loukas
