### ISSUE TITLE
Run T1K with both pair-end and singletons fastq

### ISSUE THREAD

**Issue by Gri72** [mourisl/T1K#41]
Hello,
I have pair-end and singletons fastq files. Is it proper to use -1/2 and -u flags at the same time or maybe I should concatenate files?

Thank you,
Grigory

**Comment by mourisl** [comment]
No, it doesn't support that. I think the way to handle that is to create another fastq files for the single-end file, where each sequence is the reverse complement of the original single-end file. This will create a valid paired-end files.
