### ISSUE TITLE
No multi-gene mapper

### ISSUE THREAD

**Issue by Ritabear** [mourisl/T1K#5]
Hello!

I'm trying to run this tool.
But, I have some questions about `No multi-gene mapper.`
Could you explain more about `No multi-gene mapper`?
Is it a different mode for the tool?

**Comment by mourisl** [comment]
I don't think T1K has the warning message about "No multi-gene mapper". Could you please show me the command you used? Thank you.

**Comment by Ritabear** [comment]
Sorry, I don't explain clearly.
I want to know what  Fig1a in the paper writing `No multi-gene mapper.`
I find  that  the program  has one line in `T1K_manuscript_evaluation: Fig1/Analysis.ipynb`, which writes `# No multi-gene mapper.`
Therefore, I assume `No multi-gene mapper` mean another mode.
I am curious about what is `No multi-gene mapper`  and how to use it.

**Comment by mourisl** [comment]
Thank you for the clarification.

Yes, "No multi-gene mapper" is another mode, where I added the code to ignore the reads mapped to more than one KIR gene.  The purpose is to demonstrate that ignoring multi-gene mapped reads is bad. Ignoring multiple gene mapped reads is adopted in several HLA genotypers, such as arcasHLA. It is too hard to modify arcasHLA to work with KIRs, so we add this test to mimic the behavior of arcasHLA. This mode is not really present in T1K.

Just out of curiosity, why do you need this mode?

**Comment by Ritabear** [comment]
Thank you very much!
To be honest, I don't need this mode. 
However, I saw this mode on the paper and `T1K_manuscript_evaluation: Fig1/Analysis.ipynb`.
Then, I thought `No multi-gene mapper` was a mode and couldn't find something in the helper message.
I can't suppress my curiosity and create an issue. ><

**Comment by mourisl** [comment]
Haha, then I shall close this issue for now. If you have more questions, please feel free to reopen this one or create a new issue.
